name: Preprocessing Dataset Otomatis

on:
  push:
    paths:
      - "preprocessing/automate_AuliyaSabrinaVyantika.py"
      - "namadataset_raw/creditapproval-data_raw.csv"
      - ".github/workflows/**"
  workflow_dispatch:

jobs:
  preprocessing:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.12.7"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas scikit-learn

    - name: Jalankan script preprocessing
      run: python preprocessing/automate_AuliyaSabrinaVyantika.py

    - name: Cek hasil preprocessing
      run: |
        echo "Daftar isi direktori:"
        ls -R
        echo "Isi file hasil preprocessing:"
        cat preprocessing/namadataset_preprocessing/creditapproval-data_processed.csv

    - name: Upload Hasil Preprocessing
      uses: actions/upload-artifact@v4
      with:
        name: processed-dataset
        path: preprocessing/namadataset_preprocessing/creditapproval-data_processed.csv

